import React from 'react';
import Navbar from "./src/components/Navbar";
import Footer from "./src/components/Footer";
import "./globals.css";

export const metadata = {
  title: "iSommelier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-grow pt-24">
          {children}
        </main>
        <Footer />
      </div>
      </body>
    </html>
  );
}
